/**
 * Firebase Firestore type definitions for leaderboard and match results.
 * All records include an environment field for separation between dev/prod.
 */

export interface LeaderboardScore {
  /** Document ID: auto-generated by Firestore */
  id?: string;
  /** Player display name */
  displayName: string;
  /** Survival time in seconds */
  survivalTimeSeconds: number;
  /** Final score */
  score: number;
  /** Environment: 'local' | 'development' | 'production' */
  environment: 'local' | 'development' | 'production';
  /** Timestamp when the score was recorded */
  recordedAt: Date;
}

export interface MatchResult {
  /** Document ID: auto-generated by Firestore */
  id?: string;
  /** Winner player display name, or null if no winner */
  winnerDisplayName: string | null;
  /** Array of player results, ordered by final rank */
  players: MatchResultPlayer[];
  /** Match duration in seconds */
  durationSeconds: number;
  /** Environment: 'local' | 'development' | 'production' */
  environment: 'local' | 'development' | 'production';
  /** Timestamp when the match finished */
  finishedAt: Date;
}

export interface MatchResultPlayer {
  /** Player display name */
  displayName: string;
  /** Final rank (1 = winner, 2 = second place, etc.) */
  rank: number;
  /** Survival time in seconds */
  survivalTimeSeconds: number;
  /** Final score */
  score: number;
  /** Whether this player was eliminated */
  isEliminated: boolean;
}
